import { Bai_Jamjuree } from 'next/font/google';
import './globals.css';
import NavBar from './components/shared/Navbar';
import Footer from './components/shared/Footer';

const bai_jamjuree = Bai_Jamjuree({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'AlabicaCoff',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bai_jamjuree.className} antialiased`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
